# Generated by Django 6.0.1 on 2026-04-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_pdf_pt', models.URLField(blank=True, max_length=500)),
                ('resume_pdf_en', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
