# Generated by Django 6.0.1 on 2026-04-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectAccess',
        ),
    ]
